### ISSUE TITLE
A small improvement idea - display exact angles

### ISSUE THREAD

**Issue by astibal** [MoffKalast/Sailwind-Map#2]
Hi, 
thanks for very nice navigation tool for SailWind!
I think it would be great when drawing "free form" line (grey, black, red) to have also exact angles and mile length.

I think the first one should be quite easy to do, you have co convert angle to ie "SW" anyway.
New display label might be for example "SW (225˚) - 65 NM". 

I am not frontend guy, I would send PR otherwise. It would be great addition, imo! 

Thanks,
Astib

**Comment by astibal** [comment]
Hi, thanks for response!
Exact degrees would allow better angling against visible islands and lighthouses (read the angle on compass, write to map). Even 5 degrees would help I think!
I was actually not requiring to have them permanently visible, only when drawing. 

If it's generally difficult to render as the text part of the label, I would be perfectly fine and  thankful to have it as a line in the compass picture while drawing the line, I can read the value there. Once placed, this line may disappear.
The same may go for line length.

Mock-up (process of drawing the line, not clicked to finish it):
![image](https://github.com/MoffKalast/Sailwind-Map/assets/29857469/2df00826-59be-40c1-9b0d-e141683eb2d8)

**Comment by astibal** [comment]
I am in the bed and sick, making up things when I feel better for a moment ...  I don't want to abuse your attention :) However!

Another excellent addition would be to have a possibility to add simple, fixed-size, one-line notes :) One could insert them via clicking the place, then simple popup would appear. A note font would be the same size as the map labels (ie island names). 

Why: on routine check I read the heading, speed at certain time  ... and forget all in the instant. Next nav check  I am trying to recall last check details :) Having my reading time/notes on the map would help a lot too.

**Comment by MoffKalast** [comment]
I think we best make that one into a separate issue 😃

**Comment by MoffKalast** [comment]
Added in [1351bd2](https://github.com/MoffKalast/Sailwind-Map/commit/1351bd272e8d9781712cf1210b23194f21582cd8). 

https://github.com/MoffKalast/Sailwind-Map/assets/9977799/de09fea1-8eb2-4c49-92d7-1aca563992a9

Much cleaner than before imo, thanks for the suggestion 😄

**Comment by astibal** [comment]
Thank you, it's awesome!
