### ISSUE TITLE
App Issues

### ISSUE THREAD

**Issue by Jdman6** [MoffKalast/Sailwind-Map#20]
Good afternoon. I love this map, its an amazing tool I use every time I play. When I first clicked on the link on Google it went to the map and asked me if I wanted to install the app on my pc, when I try to open the app it gives me a 404 error.

**Comment by MoffKalast** [comment]
Ah I see what you mean! I added a PWA manifest a long while back so it could launch as a fullscreen web view on Android when it's added to home screen. Looks like they've made some changes to how that works recently though, I'm seeing the same 404 when it loads that way. 

I'll look into it, thanks for the heads up 😄

**Comment by MoffKalast** [comment]
Yeah the starting url was wrong, apparently pointing it to index.html doesn't work anyway. Anyhow, should be fixed and live now. You'll have to uninstall the current one, refresh the browser version a few times so it fetches the new manifest and it should be good to go.

**Comment by Jdman6** [comment]
Thank you, I will check it out. This is really an awesome tool and I use it every time I play sailwind
