### ISSUE TITLE
Map Is Inoperable

### ISSUE THREAD

**Issue by Cojo96** [MoffKalast/Sailwind-Map#21]
As the title says, the Sailwind Interactive Map has become inoperable. It tries to load in, and after a moment, it fails to render. No information is shown, and you cannot zoom either in or out, or move anywhere on the map. See attached screenshot.
![photo_2024-10-28_10-23-41](https://github.com/user-attachments/assets/b7e8e532-addd-483f-81e4-9ba38ea65632)

**Comment by MoffKalast** [comment]
Hmm, which browser and platform? Also have you got any extensions installed? It seems to load fine for me on both Chrome and Firefox on desktop and Chrome on android.

**Comment by Cojo96** [comment]
I'm running on Opera GX browser - I tried disabling all of my extensions, so it seems to be an issue with this particular browser. Let me try running it in FireFox and report back, see if it's browser issue or something else on my end.

**Comment by Cojo96** [comment]
I can confirm it works fine for me in FireFox browser. Guess all the more reason for me to switch away from Opera GX, hah. Thank you for your quick reply, and finding the problem!

**Comment by MoffKalast** [comment]
Well that's pretty odd, I thought Opera was Chromium these days and which ought to work just as well as Chrome. If there's something like built in script blocking then that might be something that's causing it to not load. Really weird that it would be doing that by default though...
